from typing import Optional, Dict, Any
import re

class Postprocessor:
    """
    Postprocesses raw responses generated by the Vision-Language Model (VLM).

    This class extracts structured information from free-form text output,
    enabling the downstream API to interpret model predictions reliably.

    Responsibilities:
        - Extract a boolean classification flag from the response.
        - Extract a natural-language explanation.
        - Provide an extensible design for future structured metadata parsing.

    Example expected model output:
        VisibleDirtyFlag: True
        Explanation: The surface appears smudged on the right side.
    """
    def __init__(self, flag_key: str = "VisibleDirtyFlag"):
        """
        Initialize the postprocessor with a configurable flag key.

        Args:
            flag_key (str):
                The identifier the model uses to output the binary flag.
                Example: "VisibleDirtyFlag", "DamageDetectedFlag", etc.
                This key determines which field will be parsed from the text.
        """
        self.flag_key = flag_key

    def parse(self, raw_response: str) -> Dict[str, Any]:
        """
        Parse the binary flag and explanation from a raw VLM response.

        The method looks for:
            1. "<flag_key>: True/False"
            2. "Explanation: <text>"

        Args:
            raw_response (str):
                Full string output generated by the VLM.

        Returns:
            dict: A structured dictionary containing:
                - "flag": Parsed boolean value or None if not found.
                - "explanation": Extracted explanation string or None.
                - "raw": The original model response.
        """
        flag 
        flag = self._extract_flag(raw_response)
        explanation = self._extract_explanation(raw_response)

        return {
            "flag": flag,
            "explanation": explanation,
            "raw": raw_response,
        }

    def _extract_flag(self, text: str) -> Optional[bool]:
        """
        Extract the boolean flag (True/False) using a regex search.

        Expected pattern:
            "<flag_key>: True"  or  "<flag_key>: False"

        Matching is case-insensitive.
        If multiple matches exist, the last occurrence is used.

        Args:
            text (str): The raw model response.

        Returns:
            bool or None:
                True or False if found, otherwise None.
        """
        pattern = rf"{self.flag_key}\s*:\s*(True|False)"
        matches = re.findall(pattern, text, flags=re.IGNORECASE)

        if not matches:
            return None

        last = matches[-1].strip().lower()
        return True if last == "true" else False

    def _extract_explanation(self, text: str) -> Optional[str]:
        """
        Extract the explanation text following the 'Explanation:' field.

        The explanation is assumed to appear after the first occurrence of:
            "Explanation:"

        Args:
            text (str): The full model response.

        Returns:
            str or None:
                The extracted explanation text, or None if not present.
        """
        parts = re.split(r"Explanation\s*:\s*", text, flags=re.IGNORECASE)
        if len(parts) > 1:
            return parts[-1].strip()
        return None