from pydantic import BaseModel, Field
from typing import Dict, Optional

class RagVisionOutput(BaseModel):
    """
    Output schema returned by the RAG Vision Engine.

    Includes structured information about the model execution, classification
    results, timing data, and potential error messages.
    """
    success: bool = Field(..., description="Indicates whether the RAG Vision pipeline completed successfully.")
    imageId: str = Field(..., description="Identifier assigned to the processed image, useful for tracing or logging.")
    flagKey: str = Field(..., description="Identifier associated with the request, used for routing or operational logic.")
    flag: Optional[bool] = Field(None, description="Boolean decision or classification result generated by the model, if applicable.")
    explanation: Optional[str] = Field( None, description="Natural-language explanation describing the model's reasoning or justification.")
    classScores: Optional[Dict[str, float]] = Field(None, description="Dictionary mapping class labels to confidence scores produced during retrieval or classification.")
    rawResponse: Optional[str] = Field(None, description="Unprocessed or full model response text returned by the generative model.")
    elapsedTimeMs: Optional[int] = Field(None, description="Total time taken to process the request, measured in milliseconds.")
    error: Optional[str] = Field(None, description="Error message in case the request failed, used for debugging and logging.")

    @staticmethod
    def fails(imageId, flagKey, elapsedTimeMs, err):
        """
        Create a standardized failure output structure.

        Args:
            imageId (str): Identifier of the processed image.
            flagKey (str): Request routing or classification key.
            elapsedTimeMs (int): Processing time in milliseconds.
            err (str): Error message describing the failure.

        Returns:
            dict: A failure response dictionary compliant with RagVisionOutput.
        """
        return {
            "success": False,
            "imageId": imageId,
            "flagKey": flagKey,
            "elapsedTimeMs": elapsedTimeMs,
            "error": err,
        }

    @staticmethod
    def success_output(imageId, flagKey, elapsedTimeMs, flag, explanation, classScores, rawResponse):
        """
        Create a standardized success output structure.

        Args:
            imageId (str): Identifier of the processed image.
            flagKey (str): Request routing or classification key.
            elapsedTimeMs (int): Processing time in milliseconds.
            flag (bool): Model decision or classification output.
            explanation (str): Natural-language reasoning explaining the output.
            classScores (dict): Mapping of class names to confidence scores.
            rawResponse (str): Raw generative model output.

        Returns:
            dict: A success response dictionary compliant with RagVisionOutput.
        """
        return {
            "success": True,
            "imageId": imageId,
            "flagKey": flagKey,
            "elapsedTimeMs": elapsedTimeMs,
            "flag": flag,
            "explanation": explanation,
            "classScores": classScores,
            "rawResponse": rawResponse,
        }